"""tests/test_core_bridge.py

Schema-drift integration test: invoke bridge.spec(), assert top-level keys match
a snapshot stored at tests/fixtures/spec_v0.1.1.json.

On first run the snapshot is generated from actual output.
Subsequent runs compare against it.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

import pytest

sys.path.insert(0, str(Path(__file__).parent.parent))

from core.bridge import spec, version

SNAPSHOT_PATH = Path(__file__).parent / "fixtures" / "spec_v0.1.1.json"


def _top_level_keys(spec_result: dict) -> list[str]:
    return sorted(spec_result.keys())


def test_spec_schema_drift() -> None:
    """Invoke bridge.spec(); compare top-level keys against snapshot.

    First run: write snapshot. Subsequent runs: assert keys match snapshot.
    """
    result = spec()

    # Ensure snapshot dir exists
    SNAPSHOT_PATH.parent.mkdir(parents=True, exist_ok=True)

    if not SNAPSHOT_PATH.exists():
        # First run — generate snapshot
        snapshot = {
            "top_level_keys": _top_level_keys(result),
            "version": result.get("version"),
            "note": "Generated by tests/test_core_bridge.py on first run. "
                    "Commit this file to guard against schema drift.",
        }
        SNAPSHOT_PATH.write_text(json.dumps(snapshot, indent=2), encoding="utf-8")
        pytest.skip(
            f"Snapshot written to {SNAPSHOT_PATH}. "
            "Re-run tests to validate against it."
        )

    snapshot = json.loads(SNAPSHOT_PATH.read_text(encoding="utf-8"))
    expected_keys = snapshot["top_level_keys"]
    actual_keys = _top_level_keys(result)

    assert actual_keys == expected_keys, (
        f"bridge.spec() top-level keys drifted.\n"
        f"  expected: {expected_keys}\n"
        f"  actual:   {actual_keys}\n"
        f"If @google/design.md was updated intentionally, delete {SNAPSHOT_PATH} "
        f"and re-run to regenerate the snapshot."
    )

    # Also assert version hasn't silently changed
    snapped_ver = snapshot.get("version")
    actual_ver = result.get("version")
    if snapped_ver:
        assert actual_ver == snapped_ver, (
            f"@google/design.md version changed: snapshot={snapped_ver!r}, "
            f"actual={actual_ver!r}. Update the snapshot if intentional."
        )
